baseURL = 'https://iamjacke.com'
languageCode = 'en-us'
title = 'Stan Sobolev'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = 'G-HF3EGN90FY'

[minify]
  disableXML = true
  # minifyOutput = true

[params.assets]
  favicon = './favicon/favicon.ico'
  favicon16x16 = './favicon/favicon-16x16.png'
  favicon32x32 = './favicon/favicon-32x32.png'
  apple_touch_icon = './favicon/apple-touch-icon.png'
  safari_pinned_tab = './favicon/safari-pinned-tab.svg'

[menu]
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3
[[menu.main]]
  identifier = 'about'
  name = 'About'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 2